// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonMicrophone: typeof import('~icons/carbon/microphone')['default']
    ICarbonStop: typeof import('~icons/carbon/stop')['default']
    Layout: typeof import('./../src/components/Layout.vue')['default']
    Recorder: typeof import('./../src/components/Recorder.vue')['default']
    RecordingPlayer: typeof import('./../src/components/RecordingPlayer.vue')['default']
  }
}

export { }
